version: '3'

services:
  proxy:
    image: 'deus/proxy-post'
    volumes:
      - /etc/letsencrypt/live/centauro.ls.fi.upm.es/cert.pem:/proxy/ssl/cert.pem
      - /etc/letsencrypt/live/centauro.ls.fi.upm.es/privkey.pem:/proxy/ssl/key.pem
      - /home/miguel/proxy-post-logs/:/proxy/logs
    ports:
      - 4444:4444
    command: [ "node", "app.js" ]
  private-bower:
    image: 'tandrup/private-bower'
    ports:
      - 5555:5678
      - 6789:6789
      - 7891:7891
    environment:
      - ADDRESS=http://centauro.ls.fi.upm.es
    volumes:
      - ./data:/data
